// Comprehensive car data for Moova car rental PWA
// Cars distributed across Georgia
// Supports hybrid mode: Real DB data with mock fallback

export interface CarOwner {
  id: string
  firstName: string
  lastName: string
  avatarUrl: string | null
  rating: number
  responseTime: string
  tripsCount: number
  memberSince: string
  isVerified: boolean
}

export interface MapCar {
  id: string
  lat: number
  lng: number
  price: number
  pricePerHour: number
  model: string
  make: string
  year: number
  color: string
  isWinterReady: boolean
  images: string[]
  category: 'SUV' | 'SEDAN' | 'COMPACT' | 'LUXURY' | 'SPORTS'
  fuelType: 'PETROL' | 'DIESEL' | 'ELECTRIC' | 'HYBRID'
  rating: number
  reviewCount: number
  features: string[]
  isInstantBook: boolean
  transmission: 'AUTOMATIC' | 'MANUAL'
  city: CityName
  address: string
  seats: number
  doors: number
  securityDeposit: number
  mileageLimit: number | null
  owner: CarOwner
  description: string
}

// Car Owners
const OWNERS: Record<string, CarOwner> = {
  'owner-1': {
    id: 'owner-1',
    firstName: 'Giorgi',
    lastName: 'Beridze',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    rating: 4.9,
    responseTime: '< 1 hour',
    tripsCount: 47,
    memberSince: '2024',
    isVerified: true,
  },
  'owner-2': {
    id: 'owner-2',
    firstName: 'Nino',
    lastName: 'Kvlividze',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face',
    rating: 4.8,
    responseTime: '< 30 min',
    tripsCount: 31,
    memberSince: '2024',
    isVerified: true,
  },
  'owner-3': {
    id: 'owner-3',
    firstName: 'Levan',
    lastName: 'Tskhadadze',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    rating: 5.0,
    responseTime: '< 15 min',
    tripsCount: 89,
    memberSince: '2023',
    isVerified: true,
  },
  'owner-4': {
    id: 'owner-4',
    firstName: 'Tamar',
    lastName: 'Janelidze',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face',
    rating: 4.8,
    responseTime: '< 1 hour',
    tripsCount: 56,
    memberSince: '2023',
    isVerified: true,
  },
  'owner-5': {
    id: 'owner-5',
    firstName: 'Ketevan',
    lastName: 'Lomidze',
    avatarUrl: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=150&h=150&fit=crop&crop=face',
    rating: 4.9,
    responseTime: '< 30 min',
    tripsCount: 112,
    memberSince: '2022',
    isVerified: true,
  },
}

// City coordinates - All major Georgian cities
export const CITIES = {
  Tbilisi: { lat: 41.7151, lng: 44.8271, zoom: 12, label: '🏙️ Tbilisi', description: 'Capital City' },
  Batumi: { lat: 41.6168, lng: 41.6367, zoom: 13, label: '🏖️ Batumi', description: 'Black Sea Resort' },
  Kutaisi: { lat: 42.2662, lng: 42.7180, zoom: 13, label: '🏛️ Kutaisi', description: 'Second Largest City' },
  Gudauri: { lat: 42.4784, lng: 44.4842, zoom: 14, label: '🏔️ Gudauri', description: 'Ski Resort' },
  Rustavi: { lat: 41.5493, lng: 44.9939, zoom: 13, label: '🏭 Rustavi', description: 'Industrial Hub' },
  Zugdidi: { lat: 42.5088, lng: 41.8709, zoom: 13, label: '🌳 Zugdidi', description: 'Western Georgia' },
  Telavi: { lat: 41.9198, lng: 45.4731, zoom: 13, label: '🍇 Telavi', description: 'Wine Region' },
  Borjomi: { lat: 41.8428, lng: 43.3894, zoom: 14, label: '💧 Borjomi', description: 'Spa Resort' },
  Mestia: { lat: 43.0453, lng: 42.7280, zoom: 14, label: '⛰️ Mestia', description: 'Svaneti Mountains' },
  Bakuriani: { lat: 41.7510, lng: 43.5290, zoom: 14, label: '🎿 Bakuriani', description: 'Ski Resort' },
} as const

export type CityName = keyof typeof CITIES

// Working car images - using verified Unsplash photo IDs
const CAR_IMAGES = {
  // SUVs - Toyota Land Cruiser (white/silver SUVs)
  landCruiser: [
    'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80',
    'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80',
  ],
  // Hyundai Tucson (blue SUV)
  tucson: [
    'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80',
    'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80',
  ],
  // Tesla Model Y (silver electric)
  teslaY: [
    'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80',
    'https://images.unsplash.com/photo-1561580125-028ee3bd62eb?w=800&q=80',
  ],
  // BMW X5 (black luxury SUV)
  bmwX5: [
    'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80',
    'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&q=80',
  ],
  // Subaru Forester (green SUV)
  forester: [
    'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80',
    'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80',
  ],
  // Toyota RAV4 (blue compact SUV)
  rav4: [
    'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80',
    'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80',
  ],
  // Land Rover Defender (green off-road)
  defender: [
    'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800&q=80',
    'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80',
  ],
  // Kia Sportage (white SUV)
  sportage: [
    'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80',
    'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80',
  ],
  // Sedans - Toyota Camry (white sedan)
  camry: [
    'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80',
    'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80',
  ],
  // Toyota Corolla (gray sedan)
  corolla: [
    'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80',
    'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80',
  ],
  // Compact - VW Golf (red hatchback)
  golf: [
    'https://images.unsplash.com/photo-1471444928139-48c5bf5173f8?w=800&q=80',
    'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80',
  ],
  // Renault Clio (red compact)
  clio: [
    'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80',
    'https://images.unsplash.com/photo-1471444928139-48c5bf5173f8?w=800&q=80',
  ],
  // Ford Focus (gray hatchback)
  focus: [
    'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80',
    'https://images.unsplash.com/photo-1471444928139-48c5bf5173f8?w=800&q=80',
  ],
  // Luxury - Mercedes E-Class (white luxury sedan)
  eClass: [
    'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80',
    'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&q=80',
  ],
  // Mercedes GLE (black luxury SUV)
  gle: [
    'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&q=80',
    'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80',
  ],
  // Porsche Cayenne (silver sports SUV)
  cayenne: [
    'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80',
    'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80',
  ],
  // Sports - Porsche 911 (yellow sports car)
  porsche911: [
    'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80',
    'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80',
  ],
}

// All cars across Georgia - 25 cars
export const ALL_CARS: MapCar[] = [
  // ===== TBILISI (10 cars) =====
  {
    id: 'tbilisi-1',
    lat: 41.7151,
    lng: 44.8271,
    price: 120,
    pricePerHour: 18,
    model: 'Land Cruiser Prado',
    make: 'Toyota',
    year: 2023,
    color: 'Pearl White',
    isWinterReady: true,
    images: CAR_IMAGES.landCruiser,
    category: 'SUV',
    fuelType: 'DIESEL',
    rating: 4.9,
    reviewCount: 47,
    features: ['4WD/AWD', 'Snow Tires', 'Heated Seats', 'GPS Navigation', 'Ski Rack', 'Leather Seats', 'Backup Camera', 'Bluetooth'],
    isInstantBook: true,
    transmission: 'AUTOMATIC',
    city: 'Tbilisi',
    address: 'Rustaveli Avenue 12, Tbilisi',
    seats: 7,
    doors: 5,
    securityDeposit: 400,
    mileageLimit: 300,
    owner: OWNERS['owner-1'],
    description: 'Perfect for mountain trips and family adventures. This Land Cruiser Prado comes with winter tires and ski rack, making it ideal for Gudauri trips.',
  },
  {
    id: 'tbilisi-2',
    lat: 41.7089,
    lng: 44.7478,
    price: 85,
    pricePerHour: 12,
    model: 'Tucson',
    make: 'Hyundai',
    year: 2022,
    color: 'Deep Blue',
    isWinterReady: true,
    images: CAR_IMAGES.tucson,
    category: 'SUV',
    fuelType: 'PETROL',
    rating: 4.7,
    reviewCount: 32,
    features: ['4WD/AWD', 'Snow Tires', 'Backup Camera', 'Bluetooth', 'Apple CarPlay', 'Android Auto'],
    isInstantBook: true,
    transmission: 'AUTOMATIC',
    city: 'Tbilisi',
    address: 'Chavchavadze Avenue 45, Vake',
    seats: 5,
    doors: 5,
    securityDeposit: 300,
    mileageLimit: 250,
    owner: OWNERS['owner-2'],
    description: 'Modern and reliable SUV perfect for both city driving and weekend getaways. Equipped with winter package.',
  },
  {
    id: 'tbilisi-3',
    lat: 41.7215,
    lng: 44.7665,
    price: 200,
    pricePerHour: 30,
    model: 'Model Y',
    make: 'Tesla',
    year: 2024,
    color: 'Midnight Silver',
    isWinterReady: false,
    images: CAR_IMAGES.teslaY,
    category: 'SUV',
    fuelType: 'ELECTRIC',
    rating: 5.0,
    reviewCount: 18,
    features: ['Autopilot', 'Premium Audio', 'Glass Roof', 'Supercharger Access', 'Sentry Mode', 'Dog Mode'],
    isInstantBook: false,
    transmission: 'AUTOMATIC',
    city: 'Tbilisi',
    address: 'Saburtalo District, Tbilisi',
    seats: 5,
    doors: 5,
    securityDeposit: 600,
    mileageLimit: null,
    owner: OWNERS['owner-3'],
    description: 'Experience the future of driving with this fully electric Tesla Model Y. Zero emissions, maximum performance.',
  },
  {
    id: 'tbilisi-4',
    lat: 41.7320,
    lng: 44.7890,
    price: 60,
    pricePerHour: 10,
    model: 'Camry',
    make: 'Toyota',
    year: 2021,
    color: 'Classic White',
    isWinterReady: false,
    images: CAR_IMAGES.camry,
    category: 'SEDAN',
    fuelType: 'HYBRID',
    rating: 4.8,
    reviewCount: 56,
    features: ['Fuel Efficient', 'Bluetooth', 'Cruise Control', 'USB Port', 'Lane Assist', 'Adaptive Cruise'],
    isInstantBook: true,
    transmission: 'AUTOMATIC',
    city: 'Tbilisi',
    address: 'Didube District, Tbilisi',
    seats: 5,
    doors: 4,
    securityDeposit: 200,
    mileageLimit: null,
    owner: OWNERS['owner-4'],
    description: 'Economical hybrid sedan perfect for city driving. Great fuel efficiency and comfortable ride.',
  },
  {
    id: 'tbilisi-5',
    lat: 41.6934,
    lng: 44.8015,
    price: 150,
    pricePerHour: 22,
    model: 'X5',
    make: 'BMW',
    year: 2023,
    color: 'Carbon Black',
    isWinterReady: true,
    images: CAR_IMAGES.bmwX5,
    category: 'LUXURY',
    fuelType: 'DIESEL',
    rating: 4.9,
    reviewCount: 24,
    features: ['4WD/AWD', 'Snow Tires', 'Leather Seats', 'Panoramic Roof', 'Heated Steering', 'Premium Harman Kardon Audio', 'Heads-Up Display'],
    isInstantBook: true,
    transmission: 'AUTOMATIC',
    city: 'Tbilisi',
    address: 'Vera District, Tbilisi',
    seats: 5,
    doors: 5,
    securityDeposit: 500,
    mileageLimit: 200,
    owner: OWNERS['owner-1'],
    description: 'Premium luxury SUV with all the bells and whistles. Winter package included for mountain adventures.',
  },
  {
    id: 'tbilisi-6',
    lat: 41.7452,
    lng: 44.7891,
    price: 45,
    pricePerHour: 8,
    model: 'Golf',
    make: 'Volkswagen',
    year: 2022,
    color: 'Tornado Red',
    isWinterReady: false,
    images: CAR_IMAGES.golf,
    category: 'COMPACT',
    fuelType: 'PETROL',
    rating: 4.6,
    reviewCount: 38,
    features: ['Fuel Efficient', 'Bluetooth', 'USB Port', 'Air Conditioning', 'Apple CarPlay'],
    isInstantBook: true,
    transmission: 'MANUAL',
    city: 'Tbilisi',
    address: 'Gldani District, Tbilisi',
    seats: 5,
    doors: 4,
    securityDeposit: 150,
    mileageLimit: null,
    owner: OWNERS['owner-2'],
    description: 'Fun to drive compact car, perfect for navigating Tbilisi streets. Great on fuel!',
  },
  {
    id: 'tbilisi-7',
    lat: 41.7089,
    lng: 44.7856,
    price: 280,
    pricePerHour: 42,
    model: 'Cayenne',
    make: 'Porsche',
    year: 2023,
    color: 'GT Silver',
    isWinterReady: true,
    images: CAR_IMAGES.cayenne,
    category: 'LUXURY',
    fuelType: 'PETROL',
    rating: 5.0,
    reviewCount: 12,
    features: ['4WD/AWD', 'Snow Tires', 'Premium Audio', 'Sport Mode', 'Leather Interior', 'Panoramic Roof', 'PASM Suspension'],
    isInstantBook: false,
    transmission: 'AUTOMATIC',
    city: 'Tbilisi',
    address: 'Mtatsminda District, Tbilisi',
    seats: 5,
    doors: 5,
    securityDeposit: 1000,
    mileageLimit: 150,
    owner: OWNERS['owner-5'],
    description: 'Experience pure Porsche performance with the Cayenne. Luxury meets capability.',
  },
  {
    id: 'tbilisi-8',
    lat: 41.7225,
    lng: 44.8135,
    price: 95,
    pricePerHour: 14,
    model: 'Forester',
    make: 'Subaru',
    year: 2022,
    color: 'Forest Green',
    isWinterReady: true,
    images: CAR_IMAGES.forester,
    category: 'SUV',
    fuelType: 'PETROL',
    rating: 4.8,
    reviewCount: 29,
    features: ['4WD/AWD', 'Snow Tires', 'Roof Rack', 'Ski Rack', 'Heated Seats', 'EyeSight Safety'],
    isInstantBook: true,
    transmission: 'AUTOMATIC',
    city: 'Tbilisi',
    address: 'Isani District, Tbilisi',
    seats: 5,
    doors: 5,
    securityDeposit: 300,
    mileageLimit: null,
    owner: OWNERS['owner-3'],
    description: 'Adventure-ready Subaru with symmetrical AWD. Perfect for exploring Georgia.',
  },
  {
    id: 'tbilisi-9',
    lat: 41.6978,
    lng: 44.7723,
    price: 180,
    pricePerHour: 28,
    model: 'GLE',
    make: 'Mercedes-Benz',
    year: 2023,
    color: 'Obsidian Black',
    isWinterReady: true,
    images: CAR_IMAGES.gle,
    category: 'LUXURY',
    fuelType: 'DIESEL',
    rating: 4.9,
    reviewCount: 21,
    features: ['4WD/AWD', 'Snow Tires', 'MBUX System', 'Ambient Lighting', 'Air Suspension', 'Burmester Audio'],
    isInstantBook: true,
    transmission: 'AUTOMATIC',
    city: 'Tbilisi',
    address: 'Vake District, Tbilisi',
    seats: 5,
    doors: 5,
    securityDeposit: 600,
    mileageLimit: 200,
    owner: OWNERS['owner-4'],
    description: 'The ultimate luxury SUV experience with Mercedes-Benz refinement.',
  },
  {
    id: 'tbilisi-10',
    lat: 41.7381,
    lng: 44.8234,
    price: 55,
    pricePerHour: 9,
    model: 'Corolla',
    make: 'Toyota',
    year: 2023,
    color: 'Celestite Gray',
    isWinterReady: false,
    images: CAR_IMAGES.corolla,
    category: 'SEDAN',
    fuelType: 'HYBRID',
    rating: 4.7,
    reviewCount: 43,
    features: ['Fuel Efficient', 'Apple CarPlay', 'Android Auto', 'Safety Sense', 'Lane Keep Assist'],
    isInstantBook: true,
    transmission: 'AUTOMATIC',
    city: 'Tbilisi',
    address: 'Nadzaladevi District, Tbilisi',
    seats: 5,
    doors: 4,
    securityDeposit: 180,
    mileageLimit: null,
    owner: OWNERS['owner-2'],
    description: 'Reliable and efficient hybrid sedan. Toyota quality you can trust.',
  },

  // ===== BATUMI (5 cars) =====
  {
    id: 'batumi-1',
    lat: 41.6168,
    lng: 41.6367,
    price: 70,
    pricePerHour: 11,
    model: 'Corolla',
    make: 'Toyota',
    year: 2023,
    color: 'Super White',
    isWinterReady: false,
    images: CAR_IMAGES.corolla,
    category: 'SEDAN',
    fuelType: 'HYBRID',
    rating: 4.8,
    reviewCount: 34,
    features: ['Fuel Efficient', 'Apple CarPlay', 'Android Auto', 'Safety Sense'],
    isInstantBook: true,
    transmission: 'AUTOMATIC',
    city: 'Batumi',
    address: 'Batumi Boulevard, Batumi',
    seats: 5,
    doors: 4,
    securityDeposit: 200,
    mileageLimit: null,
    owner: OWNERS['owner-4'],
    description: 'Perfect for exploring Batumi and the Adjarian coast.',
  },
  {
    id: 'batumi-2',
    lat: 41.6234,
    lng: 41.6290,
    price: 55,
    pricePerHour: 9,
    model: 'Clio',
    make: 'Renault',
    year: 2022,
    color: 'Flame Red',
    isWinterReady: false,
    images: CAR_IMAGES.clio,
    category: 'COMPACT',
    fuelType: 'PETROL',
    rating: 4.5,
    reviewCount: 28,
    features: ['Fuel Efficient', 'Bluetooth', 'USB Port', 'Air Conditioning'],
    isInstantBook: true,
    transmission: 'MANUAL',
    city: 'Batumi',
    address: 'Old Batumi, Near Port',
    seats: 5,
    doors: 5,
    securityDeposit: 150,
    mileageLimit: null,
    owner: OWNERS['owner-5'],
    description: 'Nimble city car perfect for Batumi streets.',
  },
  {
    id: 'batumi-3',
    lat: 41.6089,
    lng: 41.6412,
    price: 180,
    pricePerHour: 28,
    model: 'E-Class',
    make: 'Mercedes-Benz',
    year: 2023,
    color: 'Polar White',
    isWinterReady: false,
    images: CAR_IMAGES.eClass,
    category: 'LUXURY',
    fuelType: 'DIESEL',
    rating: 4.9,
    reviewCount: 19,
    features: ['MBUX System', 'Ambient Lighting', 'Leather Seats', 'Premium Audio', 'Massage Seats'],
    isInstantBook: true,
    transmission: 'AUTOMATIC',
    city: 'Batumi',
    address: 'Sheraton Area, Batumi',
    seats: 5,
    doors: 4,
    securityDeposit: 500,
    mileageLimit: 200,
    owner: OWNERS['owner-1'],
    description: 'Arrive in style with the Mercedes E-Class. Perfect for business or pleasure.',
  },
  {
    id: 'batumi-4',
    lat: 41.6201,
    lng: 41.6523,
    price: 65,
    pricePerHour: 10,
    model: 'Sportage',
    make: 'Kia',
    year: 2022,
    color: 'Snow White Pearl',
    isWinterReady: false,
    images: CAR_IMAGES.sportage,
    category: 'SUV',
    fuelType: 'PETROL',
    rating: 4.6,
    reviewCount: 41,
    features: ['Backup Camera', 'Bluetooth', 'Cruise Control', 'Roof Rails', 'Panoramic Sunroof'],
    isInstantBook: true,
    transmission: 'AUTOMATIC',
    city: 'Batumi',
    address: 'Makhinjauri Area, Batumi',
    seats: 5,
    doors: 5,
    securityDeposit: 250,
    mileageLimit: 300,
    owner: OWNERS['owner-3'],
    description: 'Versatile SUV for beach trips and mountain escapes from Batumi.',
  },
  {
    id: 'batumi-5',
    lat: 41.6145,
    lng: 41.6298,
    price: 250,
    pricePerHour: 38,
    model: '911 Carrera',
    make: 'Porsche',
    year: 2022,
    color: 'Racing Yellow',
    isWinterReady: false,
    images: CAR_IMAGES.porsche911,
    category: 'SPORTS',
    fuelType: 'PETROL',
    rating: 5.0,
    reviewCount: 8,
    features: ['Sport Chrono Package', 'PASM', 'Bose Audio', 'Sport Exhaust', 'PDK Transmission'],
    isInstantBook: false,
    transmission: 'AUTOMATIC',
    city: 'Batumi',
    address: 'Batumi Boulevard, Premium Zone',
    seats: 2,
    doors: 2,
    securityDeposit: 1500,
    mileageLimit: 100,
    owner: OWNERS['owner-5'],
    description: 'The ultimate driving machine for the coastal highway experience.',
  },

  // ===== KUTAISI (3 cars) =====
  {
    id: 'kutaisi-1',
    lat: 42.2662,
    lng: 42.7180,
    price: 50,
    pricePerHour: 8,
    model: 'Focus',
    make: 'Ford',
    year: 2021,
    color: 'Magnetic Gray',
    isWinterReady: false,
    images: CAR_IMAGES.focus,
    category: 'COMPACT',
    fuelType: 'PETROL',
    rating: 4.4,
    reviewCount: 22,
    features: ['Fuel Efficient', 'Bluetooth', 'Air Conditioning', 'SYNC 3'],
    isInstantBook: true,
    transmission: 'MANUAL',
    city: 'Kutaisi',
    address: 'Central Kutaisi, Near Bagrati',
    seats: 5,
    doors: 5,
    securityDeposit: 150,
    mileageLimit: null,
    owner: OWNERS['owner-2'],
    description: 'Perfect for exploring Imereti region and visiting Prometheus Cave.',
  },
  {
    id: 'kutaisi-2',
    lat: 42.2712,
    lng: 42.7089,
    price: 75,
    pricePerHour: 11,
    model: 'RAV4',
    make: 'Toyota',
    year: 2022,
    color: 'Blueprint Blue',
    isWinterReady: true,
    images: CAR_IMAGES.rav4,
    category: 'SUV',
    fuelType: 'HYBRID',
    rating: 4.7,
    reviewCount: 35,
    features: ['4WD/AWD', 'Fuel Efficient', 'Backup Camera', 'Lane Assist', 'Adaptive Cruise'],
    isInstantBook: true,
    transmission: 'AUTOMATIC',
    city: 'Kutaisi',
    address: 'Kutaisi Airport Area',
    seats: 5,
    doors: 5,
    securityDeposit: 280,
    mileageLimit: null,
    owner: OWNERS['owner-4'],
    description: 'Reliable hybrid SUV perfect for exploring Western Georgia.',
  },
  {
    id: 'kutaisi-3',
    lat: 42.2598,
    lng: 42.7234,
    price: 90,
    pricePerHour: 14,
    model: 'Outlander',
    make: 'Mitsubishi',
    year: 2023,
    color: 'Pearl White',
    isWinterReady: true,
    images: CAR_IMAGES.forester,
    category: 'SUV',
    fuelType: 'HYBRID',
    rating: 4.6,
    reviewCount: 18,
    features: ['4WD/AWD', 'PHEV', '7 Seats', 'Super All-Wheel Control', 'Heated Seats'],
    isInstantBook: true,
    transmission: 'AUTOMATIC',
    city: 'Kutaisi',
    address: 'White Bridge Area, Kutaisi',
    seats: 7,
    doors: 5,
    securityDeposit: 320,
    mileageLimit: 300,
    owner: OWNERS['owner-1'],
    description: '7-seater PHEV SUV. Perfect for family trips to Martvili Canyon.',
  },

  // ===== GUDAURI (2 cars) =====
  {
    id: 'gudauri-1',
    lat: 42.4784,
    lng: 44.4842,
    price: 140,
    pricePerHour: 22,
    model: 'Land Cruiser 200',
    make: 'Toyota',
    year: 2022,
    color: 'Pearl White',
    isWinterReady: true,
    images: CAR_IMAGES.landCruiser,
    category: 'SUV',
    fuelType: 'DIESEL',
    rating: 4.9,
    reviewCount: 67,
    features: ['4WD/AWD', 'Snow Chains', 'Heated Everything', 'Ski Rack', 'Mountain Ready', 'Coolbox', 'V8 Power'],
    isInstantBook: true,
    transmission: 'AUTOMATIC',
    city: 'Gudauri',
    address: 'Gudauri Ski Resort, Main Parking',
    seats: 7,
    doors: 5,
    securityDeposit: 500,
    mileageLimit: 200,
    owner: OWNERS['owner-3'],
    description: 'The ultimate ski trip vehicle. Equipped with everything for mountain adventures.',
  },
  {
    id: 'gudauri-2',
    lat: 42.4823,
    lng: 44.4712,
    price: 160,
    pricePerHour: 25,
    model: 'Defender 110',
    make: 'Land Rover',
    year: 2023,
    color: 'Pangea Green',
    isWinterReady: true,
    images: CAR_IMAGES.defender,
    category: 'SUV',
    fuelType: 'DIESEL',
    rating: 5.0,
    reviewCount: 19,
    features: ['4WD/AWD', 'Terrain Response 2', 'Wade Sensing', 'Heated Windscreen', 'Air Suspension', 'Roof Rack'],
    isInstantBook: false,
    transmission: 'AUTOMATIC',
    city: 'Gudauri',
    address: 'Gudauri Resort, Upper Station',
    seats: 6,
    doors: 5,
    securityDeposit: 700,
    mileageLimit: 150,
    owner: OWNERS['owner-5'],
    description: 'The iconic Defender, ready for any terrain. Unstoppable in snow.',
  },

  // ===== TELAVI - Wine Region (2 cars) =====
  {
    id: 'telavi-1',
    lat: 41.9198,
    lng: 45.4731,
    price: 65,
    pricePerHour: 10,
    model: 'Camry',
    make: 'Toyota',
    year: 2022,
    color: 'Silver Metallic',
    isWinterReady: false,
    images: CAR_IMAGES.camry,
    category: 'SEDAN',
    fuelType: 'HYBRID',
    rating: 4.7,
    reviewCount: 23,
    features: ['Fuel Efficient', 'Bluetooth', 'Cruise Control', 'Comfortable Ride'],
    isInstantBook: true,
    transmission: 'AUTOMATIC',
    city: 'Telavi',
    address: 'Central Telavi, Near Batonis Tsikhe',
    seats: 5,
    doors: 4,
    securityDeposit: 200,
    mileageLimit: null,
    owner: OWNERS['owner-2'],
    description: 'Comfortable sedan for wine tour adventures in Kakheti region.',
  },
  {
    id: 'telavi-2',
    lat: 41.9156,
    lng: 45.4812,
    price: 80,
    pricePerHour: 12,
    model: 'RAV4',
    make: 'Toyota',
    year: 2023,
    color: 'Lunar Rock',
    isWinterReady: true,
    images: CAR_IMAGES.rav4,
    category: 'SUV',
    fuelType: 'HYBRID',
    rating: 4.8,
    reviewCount: 31,
    features: ['4WD/AWD', 'Roof Rack', 'Backup Camera', 'Lane Assist'],
    isInstantBook: true,
    transmission: 'AUTOMATIC',
    city: 'Telavi',
    address: 'Telavi Wine District',
    seats: 5,
    doors: 5,
    securityDeposit: 280,
    mileageLimit: null,
    owner: OWNERS['owner-4'],
    description: 'Perfect SUV for exploring the scenic Kakheti vineyards and monasteries.',
  },

  // ===== BORJOMI (1 car) =====
  {
    id: 'borjomi-1',
    lat: 41.8428,
    lng: 43.3894,
    price: 70,
    pricePerHour: 11,
    model: 'Forester',
    make: 'Subaru',
    year: 2021,
    color: 'Crystal Black',
    isWinterReady: true,
    images: CAR_IMAGES.forester,
    category: 'SUV',
    fuelType: 'PETROL',
    rating: 4.6,
    reviewCount: 19,
    features: ['4WD/AWD', 'Roof Rack', 'Heated Seats', 'EyeSight Safety'],
    isInstantBook: true,
    transmission: 'AUTOMATIC',
    city: 'Borjomi',
    address: 'Borjomi Central Park Area',
    seats: 5,
    doors: 5,
    securityDeposit: 250,
    mileageLimit: null,
    owner: OWNERS['owner-3'],
    description: 'Explore Borjomi-Kharagauli National Park with this reliable AWD Subaru.',
  },

  // ===== MESTIA (1 car) =====
  {
    id: 'mestia-1',
    lat: 43.0453,
    lng: 42.7280,
    price: 130,
    pricePerHour: 20,
    model: 'Land Cruiser Prado',
    make: 'Toyota',
    year: 2021,
    color: 'Attitude Black',
    isWinterReady: true,
    images: CAR_IMAGES.landCruiser,
    category: 'SUV',
    fuelType: 'DIESEL',
    rating: 4.9,
    reviewCount: 42,
    features: ['4WD/AWD', 'Snow Chains', 'Heated Everything', 'Ski Rack', 'Mountain Ready'],
    isInstantBook: true,
    transmission: 'AUTOMATIC',
    city: 'Mestia',
    address: 'Mestia Town Center',
    seats: 7,
    doors: 5,
    securityDeposit: 450,
    mileageLimit: 200,
    owner: OWNERS['owner-1'],
    description: 'Essential for exploring Svaneti. Handles mountain roads with ease.',
  },

  // ===== BAKURIANI (1 car) =====
  {
    id: 'bakuriani-1',
    lat: 41.7510,
    lng: 43.5290,
    price: 110,
    pricePerHour: 17,
    model: 'X5',
    make: 'BMW',
    year: 2022,
    color: 'Alpine White',
    isWinterReady: true,
    images: CAR_IMAGES.bmwX5,
    category: 'LUXURY',
    fuelType: 'DIESEL',
    rating: 4.8,
    reviewCount: 27,
    features: ['4WD/AWD', 'Snow Tires', 'Ski Rack', 'Heated Steering', 'Panoramic Roof'],
    isInstantBook: true,
    transmission: 'AUTOMATIC',
    city: 'Bakuriani',
    address: 'Bakuriani Ski Resort, Main Area',
    seats: 5,
    doors: 5,
    securityDeposit: 450,
    mileageLimit: 200,
    owner: OWNERS['owner-5'],
    description: 'Luxury winter SUV perfect for the family ski trip to Bakuriani.',
  },
]

// Get car by ID
export function getCarById(id: string): MapCar | undefined {
  return ALL_CARS.find(car => car.id === id)
}

// Filter helpers
export function getCarsByCity(city: CityName): MapCar[] {
  return ALL_CARS.filter(car => car.city === city)
}

export function getWinterReadyCars(cars: MapCar[]): MapCar[] {
  return cars.filter(car => car.isWinterReady)
}

export function getCarsByCategory(cars: MapCar[], category: MapCar['category']): MapCar[] {
  return cars.filter(car => car.category === category)
}

export function getCarsByFuelType(cars: MapCar[], fuelType: MapCar['fuelType']): MapCar[] {
  return cars.filter(car => car.fuelType === fuelType)
}

export function getHybridElectricCars(cars: MapCar[]): MapCar[] {
  return cars.filter(car => car.fuelType === 'HYBRID' || car.fuelType === 'ELECTRIC')
}

export function getTopRatedCars(cars: MapCar[], limit = 5): MapCar[] {
  return [...cars].sort((a, b) => b.rating - a.rating).slice(0, limit)
}

export function getSimilarCars(car: MapCar, limit = 4): MapCar[] {
  return ALL_CARS
    .filter(c => c.id !== car.id && (c.category === car.category || c.city === car.city))
    .slice(0, limit)
}

export function getCarsByPriceRange(cars: MapCar[], min: number, max: number): MapCar[] {
  return cars.filter(car => car.price >= min && car.price <= max)
}

// Legacy exports for backward compatibility
export const MAP_CARS = ALL_CARS.filter(car => car.city === 'Tbilisi')
export const GUDAURI_CARS = ALL_CARS.filter(car => car.city === 'Gudauri')
